config/routes.rb
Rails.application.routes.draw do

  root 'begin_pages#home'

  get '/help', to: 'begin_pages#help'

  get '/about', to: 'begin_pages#about'

  get  '/contact', to: 'begin_pages#contact'

  get '/signup', to: 'users#new'

  #post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'

  post '/login', to:'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  resources :posts, only: [:create, :destroy]

  resources :users

  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  #include ActiveModel::Model

  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140}

end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper

  private
  # ユーザーのログインを確認する
  def logged_in_user
    unless logged_in?
      #store_location
      flash[:danger] = "ログインしてください！."
      redirect_to login_url
    end
  end
end

app/controllers/begin_pages_controller.rb
class BeginPagesController < ApplicationController
  def home
    @micropost = current_user.posts.build if logged_in?
  end

  def help
  end

  def about
  end

  def contact

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]

  #include SessionsHelper

  def index
    @posts = Post.where(status:0)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params.merge(status:0))
    if @post.save
      flash[:success] = 'タスクが投稿されました'
      redirect_to posts_path
    else
      flash[:danger] = '内容を入れてください！'
      render 'posts/new'
    end
    logger.debug @post.errors.inspect

  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    flash[:success] = "内容を変更しました"
    redirect_to posts_path
  end

  def destroy
    @post = Post.find(params[:id])
    @post.update(status:1)
    flash[:success]="タスクを削除しました"
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'メールアドレスかパスワードが間違っています。'
      render 'new'
    end
  end

  def destroy
    log_out
    flash.now[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
      #@posts = @user.posts.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "こんにちは！登録に成功しました！ご登録ありがとうございます！"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

  # 正しいユーザーかどうかを確認
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/begin_pages_helper.rb
module BeginPagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper

  # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/begin_pages/about.html.erb
<% provide(:title, "このアプリについて") %>
<h1>このアプリについて</h1>
<p>
 時間の効率化を目指すために、作られたアプリ。今日するべきタスクを書き出して時間を有効的に使いましょう！
</p>
　

app/views/begin_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>お問い合わせ</h1>
<p>
  こちらから
</p>

app/views/begin_pages/help.html.erb
<% provide(:title, "ペルプ") %>
<h1>ペルプ</h1>
<p>
 お問い合わせはこちらから
</p>
　

app/views/begin_pages/home.html.erb
<% if logged_in? %>
  <div class="container">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="post_form">

      </section>
    </aside>
  </div>
<% else %>
<div class="center jumbotron">
  <h1>Time Manegement Apps</h1>
  <h2>
    時間を効率的に使いたい。そんな人のために。
  </h2>
  <%= link_to "新規登録はこちらから", signup_path, class: "btn-gradient-3d-orange" %>
</div>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Time manegement app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "ホーム", root_path, id: "home-logo"%></li>
        <li><%= link_to "ヘルプ", help_path, id: "help-logo"%></li>
        <li><%= link_to "このアプリについて", '/about' %></li>

        <% if logged_in? %>

          <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all',
                             'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application',
                             'data-turbolinks-track': 'reload' %>
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
  <![endif]-->
</head>
<body>
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "TMA", '/', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "ホーム",'/' %></li>
        <li><%= link_to "このアプリについて", '/about' %></li>
        <li><%= link_to "ログイン",'#' %></li>
      </ul>
    </nav>
  </div>
</header>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <%= yield %>
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>">
  <%= link_to gravatar_for(post.user, size: 50), post.user %>
  <span class="user"><%= link_to post.user.name, post.user %></span>
  <span class="content"><%= post.content %></span>
  <span class="timestamp">
    タスク <%= time_ago_in_words(post.created_at) %> 前.
  </span>
</li>

app/views/posts/edit.html.erb
<h1>タスク編集</h1>
<%= form_for(@post) do |f| %>
  <div><%= f.label :タイトル %></div>
  <div><%= f.text_field :title %></div>
  <div><%= f.label :内容 %></div>
  <div><%= f.text_field :content %></div>
  <%= f.submit "新しく更新する", class: "btn-gradient-3d-orange" %>

<% end %>
<%= link_to '戻る', posts_path %>

app/views/posts/index.html.erb
<h1>管理一覧</h1>
<table align="center" width="60%">
<thead>
<tr>
  <th>タイトル</th>
  <th>内容</th>
</tr>
</thead>
<tbody>
    <tr>
      <% @posts.each do |post| %>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to '編集する', edit_post_path(post) ,class: "btn-gradient-radius"%></td>
        <td><%= link_to '消す', post_path(post), method: :delete ,class: "btn-gradient-radius"%></td>
    </tr>
    <% end %>
</tbody>
</table>


<div>
<%= link_to '新しく作る！', new_post_path ,class: "btn-gradient-radius"%>
<p><%= link_to '戻る',root_path%></p>
</div>

app/views/posts/new.html.erb
<h1>新規作成</h1>
<%= form_for(@post) do |f| %>
  <div class="field">
     <%= f.label :タイトル %><br>
     <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :内容 %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit "新しく作る！", class: "btn-gradient-3d-orange" %>
  </div>
<% end %>

<%= link_to '戻る', posts_path %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "エラー") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_posts_form.html.erb
<%= form_for(@posts) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "投稿する", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "投稿一覧を見る", posts_path ,class: "btn-circle-border-double"%></span>

app/views/users/new.html.erb
<% provide(:title, '新規登録はこちら') %>
    <h1>新規登録はこちら</h1>
    <div class="center">
      <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>
          <%= render 'shared/error_messages' %>

          <%= f.label :名前 %>
          <%= f.text_field :name, class: 'form-control' %>

          <%= f.label :メールアドレス %>
          <%= f.email_field :email, class: 'form-control' %>

          <%= f.label :パスワード %>
          <%= f.password_field :password, class: 'form-control' %>

          <%= f.label :パスワード再入力, "パスワード再入力" %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>

          <%= f.submit "アカウント登録！", class: "btn-gradient-3d-orange" %>
        <% end %>
      </div>
    </div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
      <div>
        <p><%= link_to '新しく作る！', posts_path ,class: "btn-circle-border-double"%></p>
      </div>
    </section>
  </aside>
</div>